### ISSUE TITLE
missing config/vox-256.yaml

### ISSUE THREAD

**Issue by johndpope** [Songluchuan/AdaSR-TalkingHead#7]
bash run_demo.sh --source_image DEMO/demo_img_3.jpg --driving_video DEMO/demo_video_1.mp4
/media/oem/12TB/AdaSR-TalkingHead/demo.py:281: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  source_image = imageio.imread(opt.source_image)
Traceback (most recent call last):
  File "/media/oem/12TB/AdaSR-TalkingHead/demo.py", line 294, in <module>
    generator, kp_detector, he_estimator = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, gen=opt.gen, cpu=opt.cpu)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/oem/12TB/AdaSR-TalkingHead/demo.py", line 29, in load_checkpoints
    config = yaml.load(f)
             ^^^^^^^^^^^^
TypeError: load() missing 1 required positional argument: 'Loader'

UPDA
TE
does it need this too?

    parser.add_argument("--config", default='config/mix-resolution.yaml', help="path to config")
    parser.add_argument("--checkpoint", default='/checkpoints/mix-train.pth.tar', help="path to checkpoint to restore")

**Comment by vardanagarwal** [comment]
The issue isn't with the yaml file, instead with the code. In the demo.py on lines 28 and 296 it should instead be:

```
with open(config_path, 'r') as f:
    config = yaml.safe_load(f)
```
